// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;
global using System.Linq.Expressions;
using CursoEmVideo_lessons.Lesson_1;
using CursoEmVideo_lessons.Lesson_2;
using CursoEmVideo_lessons.Lesson_3;
using CursoEmVideo_lessons.Lesson_4;
using CursoEmVideo_lessons.Lesson_5;
using CursoEmVideo_lessons.Lesson_6;
using CursoEmVideo_lessons.Lesson_7;
using CursoEmVideo_lessons.Lesson_8;
using CursoEmVideo_lessons.Lesson_9;
using CursoEmVideo_lessons.Lesson_10;
using CursoEmVideo_lessons.Lesson_11;
using CursoEmVideo_lessons.Lesson_12;
using CursoEmVideo_lessons.Lesson_13;
using CursoEmVideo_lessons.Lesson_14;
using CursoEmVideo_lessons.Lesson_15;
using CursoEmVideo_lessons.Lesson_16;

public class Start
{
    public static void Main()
    {
        int selector;
        string progress;
        Console.WriteLine(
            "Lessons" + 
            "\n1 - Context" + 
            "\n2 - Classes & Objects" + 
            "\n3 - Visibility" + 
            "\n4 - Special Methods" + 
            "\n5 - Example with Objects" + 
            "\n6 - P.O.O. Pillars" + 
            "\n7 - U.E.F. Project example" + 
            "\n8 - U.E.F. relations & aggregations" + 
            "\n9 - Exercises #1" + 
            "\n10 - Inheritance (Part 1)" + 
            "\n11 - Inheritance (Part 2)" + 
            "\n12 - Polymorphism (Part 1)" + 
            "\n13 - Polymorphism (Part 2)" + 
            "\n14 - Exercises #2" + 
            "\n15 - Exercises #3" + 
            "\n16 - Final Project"
        );

        selector = int.Parse(Console.ReadLine());
        
        Selector(selector);
        
        progress = Console.ReadLine();
        
        

    }

    public static void Selector(int selector)
    {
        Console.Clear();
        switch (selector)
        {
            case 1:
            {
                _1.Lesson();
            }
                break;
            case 2:
            {
                _2.Lesson();
            }
                break;
            case 3:
            {
                _3.Lesson();
            }
                break;
            case 4:
            {
                _4.Lesson();
            }
                break;
            case 5:
            {
                _5.Lesson();
            }
                break;
            case 6:
            {
                _6.Lesson();
            }
                break;
            case 7:
            {
                _7.Lesson();
            }
                break;
            case 8:
            {
                _8.Lesson();
            }
                break;
            case 9:
            {
                _9.Lesson();
            }
                break;
            case 10:
            {
                _10.Lesson();
            }
                break;
            case 11:
            {
                _11.Lesson();
            }
                break;
            case 12:
            {
                _12.Lesson();
            }
                break;
            case 13:
            {
                _13.Lesson();
            }
                break;
            case 14:
            {
                _14.Lesson();
            }
                break;
            case 15:
            {
                _15.Lesson();
            }
                break;
            case 16:
            {
                _16.Lesson();
            }
                break;
            default:
            {
                Console.WriteLine("This options doesn't exist, try again:");
                Start.Main();
            }
                break;
        }
    }
    
    
    public int NextLesson(int selector) => selector++;

    public int PreviousLesson(int selector) => selector--;
}